"""
Django settings for flexsite project.

Generated by 'django-admin startproject' using Django 5.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import sys
from django.utils.translation import gettext_lazy as _
from django.urls import reverse_lazy

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
TESTING = "test" in sys.argv

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-^xsftv8x!jvc++0_pv+5#4-aaz1220)hm!8mtdzn%c%uh&e*^("

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    "flexelog.apps.FlexelogConfig",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "guardian",
    "django.contrib.humanize",
]

if DEBUG and not TESTING:
    INSTALLED_APPS.append("debug_toolbar")

MIDDLEWARE = [ 
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.locale.LocaleMiddleware",  # Remove if have only fixed locale
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

if not TESTING:
    MIDDLEWARE.insert(0, "debug_toolbar.middleware.DebugToolbarMiddleware")

X_FRAME_OPTIONS = "SAMEORIGIN"  # allow viewing attachments in iframe

ROOT_URLCONF = "flexsite.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "flexelog.elog_cfg.cfg_context",
            ],
        },
    },
]

WSGI_APPLICATION = "flexsite.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    "default": {                                                                                                                                    
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "flexelog.db",
        # "NAME": r"c:\git\xx_flexelog\trivia-216K-entries.db",
        #"NAME": r"c:\git\xx_flexelog\trivia-8K-entries.db",
    }
}



AUTHENTICATION_BACKENDS = (
    'django.contrib.auth.backends.ModelBackend',  # this is default
    'guardian.backends.ObjectPermissionBackend',
)


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

PASSWORD_RESET_TIMEOUT = 60  # seconds  XXX temp for testing
LOGIN_URL = reverse_lazy('login')
LOGIN_REDIRECT_URL = "/"
LOGOUT_REDIRECT_URL = reverse_lazy('login')

INTERNAL_IPS = [
    "127.0.0.1",
]

# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGES = [
    ('en', _("English")),
    ('bg', _("Bulgarian")),
    ('br', _("Brazilian")),
    ('cz', _("Czech")),
    ('de', _("German")),
    ('dk', _("Danish")),
    ('es', _("Spanish")),
    ('fr', _("French")),
    ('id', _("Indonesia")),
    ('it', _("Italian")),
    ('jp', _("Japanese")),
    ('nl', _("Dutch")),
    ('pl', _("Polish")),
    ('ru', _("Russian")),
    ('se', _("Swedish")),
    ('sk', _("Slowak")),
    ('tr', _("Turkish")),
    ('zh', _("Chinese")),
]

TIME_ZONE = "America/Toronto"  # "UTC"
USE_TZ = True  # Recommend True, dates still displayed in local timezone.

LANGUAGE_CODE = "en-us"
USE_I18N = True

LOCALE_PATHS = [
    BASE_DIR / "flexelog" / "locale",
]

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Flexelog custom -------
# Names of Groups auto-created for a new logbook
# Users are not automatically assigned to those groups
_view = ("view_entries",)
_own = ("add_entries", "edit_own_entries", "delete_own_entries",)
_others = ("edit_others_entries", "delete_others_entries")
_admin = ("configure_logbook",)

DEFAULT_LOGBOOK_GROUP_PERMISSIONS = {
    "Logbook {logbook.name} Viewers": _view,
    "Logbook {logbook.name} Contributors": _view + _own,
    "Logbook {logbook.name} Editors": _view + _own + _others,
    "Logbook {logbook.name} Admin": _view + _own + _others + _admin,
}


# ATTACHMENTS:
if DEBUG:
    MEDIA_ROOT = BASE_DIR / "media"
    MEDIA_URL = "media/"

FILE_UPLOAD_MAX_SIZE = 10485760  # 10 MiB