"""
Custom local settings for your flexelog installion.

Generated by 'django-admin startproject' using Django 5.1.4.

For more information on Django settings, see
https://docs.djangoproject.com/en/5.2/topics/settings/
and https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import sys
from pathlib import Path

# -------------------
# MANDATORY SETTINGS 
# You must set these for your local installation
# -------------------
# Generate a secret key at a command line with:
# python -c "from django.core.management.utils import get_random_secret_key; print(get_random_secret_key())"
SECRET_KEY = "ztcze7%@v2-y=@u!mzu=w$o+$&x+g^_w+aex4&70z9uyo"

# Path to where you want to store the flexelog database
# Perhaps have one subfolder for each separate server, e.g. 'home', 'work', etc.
ELOG_DIR = r"g:\My Drive\flexelog\home"  

MEDIA_ROOT = ELOG_DIR  # could add e.g. 'media', but flexelog adds 'attachments' subfolder anyway

# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    "default": {                                                                                                                                    
        "ENGINE": "django.db.backends.sqlite3",
        # "NAME": BASE_DIR / "flexelog.db",
        # "NAME": BASE_DIR / "psiport.db",
        # "NAME": r"c:\temp\gate.db",
        # "NAME": r"c:\git\xx_flexelog\trivia-216K-entries.db",
        # "NAME": r"c:\git\xx_flexelog\trivia-8K-entries.db",
        "NAME": Path(ELOG_DIR) / "home.db",
    }
}

# -----------------------------
# SETTINGS TO OPTIONALLY CHANGE IF NEEDED 
# -----------------------------
# AUTH SETTINGS
PASSWORD_RESET_TIMEOUT = 60*15  # seconds user has to use a password reset link
SESSION_EXPIRE_AT_BROWSER_CLOSE = False
SESSION_COOKIE_AGE = 14 * 60 * 60 * 24  # 60*60*24 = one day

# TIME ZONE / LANGUAGE
TIME_ZONE = "America/Toronto"
USE_TZ = True  # Recommend True, dates still displayed in local timezone.
LANGUAGE_CODE = "en-us"
USE_I18N = True  # Recommend True, gives translations where available

# Names of Groups auto-created for a new logbook
# Users are not automatically assigned to those groups
_view = ("view_entries",)
_own = ("add_entries", "edit_own_entries", "delete_own_entries",)
_others = ("edit_others_entries", "delete_others_entries")
_admin = ("configure_logbook",)

DEFAULT_LOGBOOK_GROUP_PERMISSIONS = {
    "Logbook {logbook.name} Viewers": _view,
    "Logbook {logbook.name} Contributors": _view + _own,
    "Logbook {logbook.name} Editors": _view + _own + _others,
    "Logbook {logbook.name} Admin": _view + _own + _others + _admin,
}

# ATTACHMENTS:
FILE_UPLOAD_MAX_SIZE = 104_857_600  # 100 MiB